cmd_drivers/mtk_wcn_combo/drv_wlan/wlan/os/linux/hif/sdio/arm.o := ../android/prebuilt/linux-x86/toolchain/arm-linux-androideabi-4.4.x/bin/arm-linux-androideabi-gcc -Wp,-MD,drivers/mtk_wcn_combo/drv_wlan/wlan/os/linux/hif/sdio/.arm.o.d  -nostdinc -isystem ../android/prebuilt/linux-x86/toolchain/arm-linux-androideabi-4.4.x/bin/../lib/gcc/arm-linux-androideabi/4.4.3/include -I/home/eason/Project/ramos_source/kernel/arch/arm/include -Iarch/arm/include/generated -Iinclude  -include include/generated/autoconf.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-exynos/include -Iarch/arm/plat-s5p/include -Iarch/arm/plat-samsung/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -marm -fno-dwarf2-cfi-asm -fno-omit-frame-pointer -mapcs -mno-sched-prolog -mabi=aapcs-linux -mno-thumb-interwork -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -fno-stack-protector -fno-omit-frame-pointer -fno-optimize-sibling-calls -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DLINUX -DMT6620 -fno-pic -DCFG_SUPPORT_WAPI=0 -DCFG_SUPPORT_XLOG=0 -D_HIF_SDIO=1 -DDBG=0 -Idrivers/mtk_wcn_combo/drv_wlan/wlan/os -Idrivers/mtk_wcn_combo/drv_wlan/wlan/os/linux/include -Idrivers/mtk_wcn_combo/drv_wlan/wlan/os/linux/hif/sdio/include -Idrivers/mtk_wcn_combo/drv_wlan/wlan/include -Idrivers/mtk_wcn_combo/drv_wlan/wlan/include/nic -Idrivers/mtk_wcn_combo/drv_wlan/wlan/include/mgmt -O2  -DMODULE -fno-pic -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(arm)"  -D"KBUILD_MODNAME=KBUILD_STR(wlan)" -c -o drivers/mtk_wcn_combo/drv_wlan/wlan/os/linux/hif/sdio/arm.o drivers/mtk_wcn_combo/drv_wlan/wlan/os/linux/hif/sdio/arm.c

source_drivers/mtk_wcn_combo/drv_wlan/wlan/os/linux/hif/sdio/arm.o := drivers/mtk_wcn_combo/drv_wlan/wlan/os/linux/hif/sdio/arm.c

deps_drivers/mtk_wcn_combo/drv_wlan/wlan/os/linux/hif/sdio/arm.o := \

drivers/mtk_wcn_combo/drv_wlan/wlan/os/linux/hif/sdio/arm.o: $(deps_drivers/mtk_wcn_combo/drv_wlan/wlan/os/linux/hif/sdio/arm.o)

$(deps_drivers/mtk_wcn_combo/drv_wlan/wlan/os/linux/hif/sdio/arm.o):
